### ISSUE TITLE
Troubleshoot Access Assignment warnings and failures

### ISSUE THREAD

**Issue by MisterCloudTech** [microsoft/PartnerCenter-GDAPTransition#17]
When running step **9. Create Security Group-Role Assignment(s)**, all of the processed assignments is listed as "...-Created", except one where this message is displayed: 
"-Please check input setup for gdaprelationships and securitygroup configuration."

In the accessAssignment.csv file, all of the assignments are in "Pending" state - except one with status "Failed".
No further information is provided to indicate which of the assignments the errors are related to.

The documentation does not discuss were to locate more detailed information for troubleshooting purposes. Is this available ?

How can I locate which of the Security Groups assignments are the one with an error ? 

The warning on screen and the Failed error appear to be in two different places in processing sequence - I have tried to count through the steps, but cannot locate any errors in either places.

Thanks

**Comment by sansbacher** [comment]
Unfortunately I don't know. Things I can suggest would be:

1. Check the Logs folder (\GBM\Logs\LogFile08292022.txt - where 08292022 is the date in MMDDYYYY format, because that makes most sense :)
2. Confirm the Roles you are trying to use are in: GBM\Configuration\ADRoleTemplatesAll.json (which it seems to be, under Global - and I know Global Admin works)
3. Edit appsettings.json (in the same Configuration folder) and see if you can change the LogLevel for Default and/or Microsoft and re-run your batch. Valid options are listed here: [Microsoft.Extensions.Logging](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=dotnet-plat-ext-6.0) (the lower the number the more info, so try Debug or Trace)

I don't think I tried that Role so I can't say if it worked for me.

**Comment by MisterCloudTech** [comment]
Investigating the logs unfortunately did not bring me further, but after going though the files in details, I found a wrong reference in the securityGroup.csv file, where the group ID was not correct. After correcting this, the error was gone.

**Comment by MisterCloudTech** [comment]
Investigating the logs unfortunately did not bring me further, but after going though the files in details, I found a wrong reference in the securityGroup.csv file, where the group ID was not correct. After correcting this, the error was gone.

**Comment by sansbacher** [comment]
Good to know. If it helps: I recently found out that `securityGroup.csv` will accept the **Role Name** in the _CommaSeperatedRoles_ column, which can make finding mistakes easier. 

For example, I have this in my most recent test and it worked:
```
Id,DisplayName,CommaSeperatedRoles
806980ff-1234-5678-abcd-c2d3a55fc7c4,GDAP-Full Access,"Global Administrator, Global Reader"
```


Maybe that'll help in the future!
  --Saul
